title: 阿咒的浮生日记
description: > # this means to ignore newlines until "baseurl:"
  看一次给五块钱
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://norohime.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "hime_noro" #if your site has a twitter account, enter it here

# Author Settings
author: Noro # add your name
author-img: yuno.jpg # add your photo
about-author: > # add description
  我房子还蛮小的<br />
  来了就别想走了
social-twitter: hime_noro # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: norohime # add your Github handle
# social-linkedin: # add your Linkedin handle
social-email: SakuraSaki@live.cn # add your Email address
social-discord: vCw7SG2
social-qq: 1453972593
social-steam: norohime
social-bili: 1496630
social-weibo: 1005053507700821
social-coolapk: 604592
social-netease: 63407587
# Disqus
discus-identifier: noro # add your discus identifier

# Tracker
analytics: UA-153494546-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
